"""
Multi-database Django settings for MongoDB + PostgreSQL.

Configures both databases simultaneously:
- "default": MongoDB (for application models)
- "postgresql": PostgreSQL (for Django built-in apps: auth, admin, contenttypes, sessions)

DATABASE_ROUTERS routes built-in Django apps to PostgreSQL and application models to
MongoDB. See routers.PostgreSQLRouter for details.

Requirements:
- pip install -e ".[postgres]"
- Set MONGODB_URI environment variable
"""

from .base import *  # noqa

import os

import dj_database_url

# Use MongoDB's ObjectId for application models.
# Django built-in models (auth, admin, contenttypes) already declare integer PKs
# explicitly, so DEFAULT_AUTO_FIELD does not affect them.
DEFAULT_AUTO_FIELD = "django_mongodb_backend.fields.ObjectIdAutoField"

# Add MongoDB extensions to installed apps (guard against duplicate if mongodb.py was also imported)
if "django_mongodb_extensions" not in INSTALLED_APPS:  # noqa: F405
    INSTALLED_APPS += ["django_mongodb_extensions"]  # noqa: F405

# Multi-database configuration: MongoDB as default, PostgreSQL as secondary
DATABASES = {
    "default": {
        "ENGINE": "django_mongodb_backend",
        "HOST": os.getenv("MONGODB_URI"),
        "NAME": "{{ project_name }}",
    },
    "postgresql": dj_database_url.config(
        default="postgres://postgres:postgres@localhost:5432/{{ project_name }}",
        conn_max_age=600,
        conn_health_checks=True,
    ),
}

# Add both MQL Panel and SQL Panel to debug toolbar (guard against duplicates)
if "django_mongodb_extensions.mql_panel.MQLPanel" not in DEBUG_TOOLBAR_PANELS:  # noqa: F405
    DEBUG_TOOLBAR_PANELS.insert(  # noqa: F405
        DEBUG_TOOLBAR_PANELS.index("debug_toolbar.panels.staticfiles.StaticFilesPanel"),  # noqa: F405
        "django_mongodb_extensions.mql_panel.MQLPanel",
    )
if "debug_toolbar.panels.sql.SQLPanel" not in DEBUG_TOOLBAR_PANELS:  # noqa: F405
    DEBUG_TOOLBAR_PANELS.insert(  # noqa: F405
        DEBUG_TOOLBAR_PANELS.index("debug_toolbar.panels.staticfiles.StaticFilesPanel"),  # noqa: F405
        "debug_toolbar.panels.sql.SQLPanel",
    )

# PostgreSQLRouter must come before MongoRouter so that Django built-in apps are
# claimed by PostgreSQL before MongoRouter routes everything else to MongoDB.
DATABASE_ROUTERS = [
    "{{ project_name }}.routers.PostgreSQLRouter",
    "django_mongodb_backend.routers.MongoRouter",
]

# No custom migration modules needed:
# - Django built-ins use standard PostgreSQL migrations (routed by PostgreSQLRouter)
# - Application models use MongoDB migrations generated by makemigrations
MIGRATION_MODULES = {}
