QE_INSTALLED_APPS = [
    "medical_records",
]

# Queryable Encryption (QE) Configuration
# Uncomment and configure these settings to enable Queryable Encryption.
# See: https://django-mongodb-backend.readthedocs.io/en/latest/howto/queryable-encryption/
#
# Requirements:
# - MongoDB 7.0+ (replica set or sharded cluster)
# - pip install 'django-mongodb-backend[encryption]'
# - Download Automatic Encryption Shared Library from MongoDB
#
# from pymongo.encryption_options import AutoEncryptionOpts
#
# DATABASES = {
#     "default": {
#         "ENGINE": "django_mongodb_backend",
#         "HOST": os.getenv("MONGODB_URI", "mongodb+srv://cluster0.example.mongodb.net"),  # noqa: F405
#         "NAME": "{{ project_name }}",
#     },
#     # Encrypted database connection with AutoEncryptionOpts
#     "encrypted": {
#         "ENGINE": "django_mongodb_backend",
#         "HOST": os.getenv("MONGODB_URI", "mongodb+srv://cluster0.example.mongodb.net"),  # noqa: F405
#         "NAME": "{{ project_name }}_encrypted",
#         "OPTIONS": {
#             "auto_encryption_opts": AutoEncryptionOpts(
#                 key_vault_namespace="{{ project_name }}_encrypted.__keyVault",
#                 kms_providers={
#                     # Local KMS provider (for development only)
#                     "local": {
#                         # Generated by os.urandom(96)
#                         "key": (
#                             b"-\xc3\x0c\xe3\x93\xc3\x8b\xc0\xf8\x12\xc5#b"
#                             b"\x19\xf3\xbc\xccR\xc8\xedI\xda\\ \xfb\x9cB"
#                             b"\x7f\xab5\xe7\xb5\xc9x\xb8\xd4d\xba\xdc\x9c"
#                             b"\x9a\xdb9J]\xe6\xce\x104p\x079q.=\xeb\x9dK*"
#                             b'\x97\xea\xf8\x1e\xc3\xd49K\x18\x81\xc3\x1a"'
#                             b'\xdc\x00U\xc4u"X\xe7xy\xa5\xb2\x0e\xbc\xd6+-'
#                             b"\x80\x03\xef\xc2\xc4\x9bU"
#                         )
#                     },
#                     # For production, use a KMS provider like AWS:
#                     # "aws": {
#                     #     "accessKeyId": os.getenv("AWS_ACCESS_KEY_ID"),  # noqa: F405
#                     #     "secretAccessKey": os.getenv("AWS_SECRET_ACCESS_KEY"),  # noqa: F405
#                     # },
#                 },
#                 # Exact file name depends on your operating system.
#                 crypt_shared_lib_path=os.getenv("CRYPT_SHARED_LIB_PATH"),  # noqa: F405
#                 crypt_shared_lib_required=True,
#                 # In production, add encrypted_fields_map from showencryptedfieldsmap
#                 # encrypted_fields_map=json_util.loads("""..."""),
#             )
#         },
#         # For production KMS (e.g., AWS):
#         # "KMS_CREDENTIALS": {
#         #     "aws": {
#         #         "key": "arn:aws:kms:...",  # Amazon Resource Name
#         #         "region": "us-east-1",
#         #     },
#         # },
#     },
#     # Uncomment to add a second database connection for the Django test suite:
#     # "other": {
#     #     "ENGINE": "django_mongodb_backend",
#     #     "HOST": os.getenv("MONGODB_URI", "mongodb://localhost:27017"),
#     #     "NAME": "{{ project_name }}_other",
#     # },
# }
#
# # Database router for encrypted models
# # The EncryptedRouter is already included in {{ project_name }}/routers.py
# # It automatically routes models with encrypted fields to the "encrypted" database
# DATABASE_ROUTERS = [
#     "django_mongodb_backend.routers.MongoRouter",
#     "{{ project_name }}.routers.EncryptedRouter",
# ]
#
# # After configuring, run:
# # python manage.py migrate --database encrypted
# # python manage.py showencryptedfieldsmap --database encrypted
